version: '3'

services:
    php:
        build:
            context: .
        depends_on:
            - db
        env_file:
            - .env
        volumes:
            - .:/srv/api:rw
    api:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        depends_on:
            - php
        ports:
            - "${CORE_NGINX_PORTS:-80}"
        volumes:
            - .:/srv/api:ro
    db:
        image: mysql:5.7
        ports:
          - "${CORE_DB_PORTS:-3306}"
        environment:
          - MYSQL_USER=core
          - MYSQL_PASSWORD=core
          - MYSQL_DATABASE=core
          - MYSQL_RANDOM_ROOT_PASSWORD=true
        volumes:
          - db-data:/var/lib/postgresql/data:rw
volumes:
    db-data: {}
#        # In production, you may want to use a managed database service
#        image: postgres:9.6-alpine
#        environment:
#            - POSTGRES_DB=api
#            - POSTGRES_USER=api-platform
#            # You should definitely change the password in production
#            - POSTGRES_PASSWORD=!ChangeMe!
#        volumes:
#            - db-data:/var/lib/postgresql/data:rw
#            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#            # - ./docker/db/data:/var/lib/postgresql/data:rw
#        ports:
#            - "5432:5432"

