Core\Main\Domain\Model\Metadata:
  type: entity
  table: metadata
  repositoryClass: Core\Main\Infrastructure\Domain\Model\DoctrineMetadataRepository
  id:
    id:
      column: id
  fields:
    name:
      type: string
      length: 50
    type:
      type: string
      length: 20
  manyToOne:
    parent:
      targetEntity: Core\Main\Domain\Model\Metadata
      joinColumn:
        name: parent_id
        referencedColumnName: id
