Core\Main\Domain\Model\Metadata:
  type: entity
  table: metadata
  repositoryClass: Core\Main\Infrastructure\Domain\Model\DoctrineMetadataRepository
  id:
    id:
      column: id
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50
    type:
      type: string
      length: 20
    values:
      type: string
      length: 255
      column: `values`
      nullable: true
  manyToOne:
    parent:
      targetEntity: Core\Main\Domain\Model\Metadata
      joinColumn:
        name: parent_id
        referencedColumnName: id
