Core\Main\Domain\Model\Test\Test:
  type: entity
  id:
    id:
      column: id
      type: guid
  table: tests
  repositoryClass: Core\Main\Infrastructure\Domain\Model\Test\DoctrineTestRepository
  fields:
    name:
      type: string
      length: 255
    minAge:
      type: integer
      column: min_age
      nullable: true
    maxAge:
      type: integer
      column: max_age
      nullable: true
    pointsRequired:
      type: integer
      column: points_required
      nullable: true
    notes:
      type: string
      lenght: 500
      nullable: true
  manyToMany:
    units:
      targetEntity: Core\Main\Domain\Model\Unit\Unit
      joinTable:
        name: test_units
        joinColumns:
          test_id:
            referencedColumnName: id
        inverseJoinColumns:
          unit_id:
            referencedColumnName: id
  manyToOne:
    cognitiveSkill:
      targetEntity: Core\Main\Domain\Model\Test\CognitiveSkill
      joinColumn:
        name: cognitive_skill_id
        referencedColumnName: id
    methodology:
      targetEntity: Core\Main\Domain\Model\Test\Methodology
      joinColumn:
        name: methodology_id
        referencedColumnName: id
    creator:
      targetEntity: Core\Main\Domain\Model\User\User
      joinColumn:
        name: creator_id
        referencedColumnName: id
