Core\Main\Domain\Model\Image:
  type: entity
  table: images
  repositoryClass: Core\Main\Infrastructure\Domain\Model\DoctrineImageRepository
  id:
    id:
      column: id
      type: integer
      generator:
        strategy: AUTO
  fields:
    src:
      type: string
    createdAt:
      type: datetime
      column: created_at
  oneToMany:
    imageMetadata:
      targetEntity: Core\Main\Domain\Model\ImageMetadata
      mappedBy: image
  manyToOne:
    creator:
      targetEntity: Core\Main\Domain\Model\User\User
      joinColumn:
        name: creator_id
        referencedColumnName: id
