Core\Main\Domain\Model\Test\CognitiveSkill:
  type: entity
  id:
    id:
      column: id
      type: guid
  table: cognitive_skills
  repositoryClass: Core\Main\Infrastructure\Domain\Model\Test\DoctrineCognitiveSkillRepository
  fields:
    name:
      type: string
      length: 500
  manyToMany:
    cognitiveTypes:
      targetEntity: Core\Main\Domain\Model\Test\CognitiveType
      joinTable:
        name: cognitive_skill_types
        joinColumns:
          cognitive_skill_id:
            referencedColumnName: id
        inverseJoinColumns:
          cognitive_type_id:
            referencedColumnName: id

