Core\Main\Domain\Model\User\ResetPassword:
  type: entity
  id:
    id:
      column: id
      type: string

  table: users_reset_passwords
  repositoryClass: Core\Main\Infrastructure\Domain\Model\User\DoctrineUserResetPasswordRepository
  uniqueConstraints:
    id_user_index:
      columns: [id, user_id]
  fields:
    userId:
      column: user_id
      type: guid
    expiresAt:
      type: datetime
      column: expires_at
    resetAt:
      type: datetime
      nullable: true
      column: reset_at
    createdAt: 
      type: datetime
      column: created_at
