Core\Main\Domain\Model\Unit\Unit:
  type: entity
  id:
    id:
      column: id
      type: guid
  table: units
  repositoryClass: Core\Main\Infrastructure\Domain\Model\Unit\DoctrineUnitRepository
  fields:
    name:
      type: string
      length: 255
    text:
      type: string
      length: 255
    rows:
      type: integer
    cols:
      type: integer
    type:
      type: string
      column: "`type`"
      length: 20
    timeToConduct:
      type: integer
      column: time_to_conduct
      nullable: true
  oneToMany:
    unitImages:
      targetEntity: Core\Main\Domain\Model\Unit\UnitImage
      mappedBy: unit
  manyToOne:
    cognitiveType:
      targetEntity: Core\Main\Domain\Model\Test\CognitiveType
      joinColumn:
        name: cognitive_type_id
        referencedColumnName: id
    cognitiveSubtype:
      targetEntity: Core\Main\Domain\Model\Test\CognitiveType
      joinColumn:
        name: cognitive_subtype_id
        referencedColumnName: id
