Core\Main\Domain\Model\Unit\Category:
  type: entity
  id:
    id:
      column: id
      type: guid
  table: categories
  repositoryClass: Core\Main\Infrastructure\Domain\Model\Unit\DoctrineCategoryRepository
  fields:
    name:
      type: string
      length: 255
